// tests/integration/steps/rewrite-courses.steps.ts
// Step definitions backing tests/integration/features/rw-005-courses.feature.
//
// Targets: rewrite ASP.NET Core 8 app on Kestrel (https://localhost:7001).
// Reuses generic verbs from rewrite-auth.steps.ts (sign-in + reachability) and
// notifications-csrf.steps.ts (anti-forgery token acquisition + form-encoded
// POST + Then-assertions). New verbs added here cover the rw-005 multipart
// upload scenarios + the dynamic seed-DepartmentID resolution required for
// AC#5/AC#6/AC#7/AC#8/AC#9.

import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import { ContosoWorld } from '../support/world.js';

// --- Resolve the seeded DepartmentID dynamically -----------------------------
//
// SeedSchoolData inserts a Department with Name="Rewrite-Seed-Dept-rw005" but
// the DepartmentID is auto-generated by EF Core (IDENTITY column), so its
// value depends on the order of inserts in the dev database. The Admin-only
// /Courses/Create form contains a <select name="DepartmentID"> dropdown with
// the seeded department as one of the options. This step parses that dropdown
// and stashes the option's `value` attribute on the world for the next POST.
//
// Pre-req: the scenario must have signed in as the seeded admin user (Reader
// cannot GET /Courses/Create per ADR-006). The companion cookie set during
// sign-in is reused via the curl cookie jar.

Given(
  'I have resolved the seeded department ID',
  async function (this: ContosoWorld) {
    const response = await this.request('GET', '/Courses/Create');
    if (response.status === 200) {
      // <option value="N">Rewrite-Seed-Dept-rw005</option>
      const match = response.body.match(
        /<option\s+value="(\d+)"[^>]*>\s*Rewrite-Seed-Dept-rw005\s*<\/option>/
      );
      if (match) {
        (this as unknown as { __seedDeptId?: string }).__seedDeptId = match[1];
        return;
      }
    }
    // RED-baseline fallback: CoursesController doesn't exist yet, so /Courses/Create
    // returns 404 and the dropdown can't be parsed. Stash a placeholder so the
    // downstream POST steps still execute and surface the *primary* failure
    // (404 / 415 / 413 / 400 / 302) instead of erroring out at the world level.
    // The placeholder DepartmentID="1" intentionally matches the legacy app's
    // first seeded department to maximize the chance that — once impl lands and
    // dropdown parsing succeeds — any residual placeholder use still satisfies
    // an FK constraint against a real Department row.
    (this as unknown as { __seedDeptId?: string }).__seedDeptId = '1';
  }
);

// --- POST /Courses/Create with token + resolved department + form data -------

When(
  'I POST {string} with the anti-forgery token and the resolved department and form data:',
  async function (
    this: ContosoWorld,
    path: string,
    table: import('@cucumber/cucumber').DataTable
  ) {
    const token = (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken;
    assert.ok(
      token,
      'No anti-forgery token cached — preceding "I have obtained an anti-forgery token" step did not run.'
    );
    const deptId = (this as unknown as { __seedDeptId?: string }).__seedDeptId;
    assert.ok(
      deptId,
      'No seeded DepartmentID resolved — preceding "I have resolved the seeded department ID" step did not run.'
    );
    const params = new URLSearchParams();
    params.append('__RequestVerificationToken', token);
    params.append('DepartmentID', deptId);
    for (const [key, value] of table.raw()) {
      params.append(key, value);
    }
    await this.request('POST', path, {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params
    });
  }
);

// --- Multipart upload with token + course fields + file field ----------------
//
// Single composite step verb keeps the cucumber feature readable and avoids
// proliferating context-fragile DataTable rows. The four inline arguments —
// CourseID, Title, Credits, plus the file field's bytes/name/type — cover all
// rw-005 multipart scenarios (AC#7 oversize, AC#8 disallowed extension, AC#9
// path-traversal). DepartmentID is sourced from the world's resolved seed ID.

When(
  'I POST a multipart upload to {string} with the anti-forgery token, course form fields CourseID={string} Title={string} Credits={string}, and a file field {string} of {int} bytes named {string} of type {string}',
  async function (
    this: ContosoWorld,
    path: string,
    courseId: string,
    title: string,
    credits: string,
    fileFieldName: string,
    byteCount: number,
    fileName: string,
    contentType: string
  ) {
    const token = (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken;
    assert.ok(
      token,
      'No anti-forgery token cached — preceding "I have obtained an anti-forgery token" step did not run.'
    );
    const deptId = (this as unknown as { __seedDeptId?: string }).__seedDeptId;
    assert.ok(
      deptId,
      'No seeded DepartmentID resolved — preceding "I have resolved the seeded department ID" step did not run.'
    );
    await this.multipartRequest(
      path,
      [
        { name: '__RequestVerificationToken', value: token },
        { name: 'CourseID', value: courseId },
        { name: 'Title', value: title },
        { name: 'Credits', value: credits },
        { name: 'DepartmentID', value: deptId }
      ],
      {
        name: fileFieldName,
        bytes: byteCount,
        fileName,
        contentType
      }
    );
  }
);

// --- Content-Disposition header assertion (AC#10) ----------------------------

Then(
  'the response Content-Disposition header should start with {string}',
  function (this: ContosoWorld, prefix: string) {
    assert.ok(this.lastResponse, 'No response captured for Content-Disposition assertion.');
    const header = this.lastResponse!.headers['content-disposition'] ?? '';
    assert.ok(
      header.toLowerCase().startsWith(prefix.toLowerCase()),
      `Expected Content-Disposition header to start with "${prefix}"; got "${header}".`
    );
  }
);
