// tests/integration/steps/rewrite-instructors.steps.ts
// Step definitions backing tests/integration/features/rw-006-instructors.feature.
//
// Targets: rewrite ASP.NET Core 8 app on Kestrel (https://localhost:7001).
// Reuses generic verbs from rewrite-auth.steps.ts (sign-in + reachability) and
// notifications-csrf.steps.ts (anti-forgery token acquisition + form-encoded
// POST + Then-assertions). New verbs added here cover the rw-006
// master/detail/sub-detail Index navigation + the OfficeAssignment +
// CourseAssignment matrix POSTs that drive the most complex CRUD controller
// in F-003.

import { Given, When } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import { ContosoWorld } from '../support/world.js';

// --- Resolve the seeded InstructorID dynamically -----------------------------
//
// SeedSchoolData inserts an Instructor with LastName="Rewrite-Seed-Instructor-rw006"
// but its Person.ID is auto-generated by EF Core (IDENTITY column), so the value
// depends on the order of inserts. The /Instructors page (Reader-visible per
// ADR-006) renders each instructor row with a stable HTML hook so the cucumber
// scenarios can resolve the integer ID at runtime — we look for a link of the
// form `/Instructors/Details/{id}` whose neighbouring text contains the seed
// LastName marker.
//
// Pre-req: the scenario must have signed in (Reader or Admin) before calling
// this step — the /Instructors index requires authentication.

Given(
  'I have resolved the seeded instructor ID for rw-006',
  async function (this: ContosoWorld) {
    const response = await this.request('GET', '/Instructors');
    if (response.status === 200) {
      // Search for a Details link whose row contains the seed LastName marker.
      // The Index view renders each row as a <tr> containing the LastName text
      // and a Details/Edit/Delete link group with asp-route-id="@item.ID".
      // We use a tolerant regex that accepts either the absolute or relative
      // URL form and either ordering of the LastName / link.
      const body = response.body;
      const markerIdx = body.indexOf('Rewrite-Seed-Instructor-rw006');
      if (markerIdx !== -1) {
        // Look ahead and behind ~600 chars for an /Instructors/Details/{id}
        // link associated with this row.
        const windowStart = Math.max(0, markerIdx - 600);
        const windowEnd = Math.min(body.length, markerIdx + 600);
        const window = body.substring(windowStart, windowEnd);
        const match =
          window.match(/\/Instructors\/Details\/(\d+)/) ??
          window.match(/\/Instructors\/Edit\/(\d+)/) ??
          window.match(/\/Instructors\?id=(\d+)/);
        if (match) {
          (this as unknown as { __seedInstructorId?: string }).__seedInstructorId = match[1];
          return;
        }
      }
    }
    // RED-baseline fallback: InstructorsController doesn't exist yet, so
    // /Instructors returns 404 and the row can't be parsed. Stash a placeholder
    // so the downstream steps still execute and surface the *primary* failure
    // (404 / 403 / 302) instead of erroring out at the world level. The
    // placeholder ID="1" intentionally targets the legacy seed Instructor
    // (rw-003 SeedSchoolData inserted "Seed, Rewrite") to keep FK hits realistic.
    (this as unknown as { __seedInstructorId?: string }).__seedInstructorId = '1';
  }
);

// --- Resolve the seeded CourseID for the M:N target --------------------------
//
// rw-005 SeedSchoolData inserts a Course with CourseID=99001 (pinned, NOT
// auto-generated). We expose this as a constant — no parsing needed — but
// declare a step verb so the feature file reads naturally.

const SEED_COURSE_ID = '99001';

// --- Master/detail/sub-detail Index navigation -------------------------------

When(
  'I GET the seeded instructor index page with the instructor selected',
  async function (this: ContosoWorld) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    await this.request('GET', `/Instructors?id=${id}`);
  }
);

When(
  'I GET the seeded instructor index page with the instructor and seeded course selected',
  async function (this: ContosoWorld) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    await this.request('GET', `/Instructors?id=${id}&courseID=${SEED_COURSE_ID}`);
  }
);

When(
  'I GET the seeded instructor details page',
  async function (this: ContosoWorld) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    await this.request('GET', `/Instructors/Details/${id}`);
  }
);

When(
  'I GET the seeded instructor edit page',
  async function (this: ContosoWorld) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    await this.request('GET', `/Instructors/Edit/${id}`);
  }
);

// --- Anti-forgery token acquisition from the seeded edit page ----------------

Given(
  'I have obtained an anti-forgery token from the seeded instructor edit page',
  async function (this: ContosoWorld) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    const response = await this.request('GET', `/Instructors/Edit/${id}`);
    if (response.status === 200) {
      const token = this.extractAntiForgeryToken(response.body);
      assert.ok(
        token,
        `Could not extract an anti-forgery token from /Instructors/Edit/${id}.`
      );
      (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken = token!;
      return;
    }
    // RED-baseline fallback: Edit page doesn't exist yet, so we cache an empty
    // token. The downstream POST surfaces the *primary* failure (404 → because
    // POST endpoint doesn't exist) instead of erroring out at the assertion.
    (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken = '';
  }
);

// --- POST /Instructors/Create with OfficeAssignment + selectedCourses[] ------
//
// The Create form renders:
//   - LastName text input
//   - FirstMidName text input
//   - HireDate date input
//   - OfficeAssignment.Location text input (the dotted name binds the nested
//     OfficeAssignment property via TryUpdateModel — legacy F-003 FR-F-003-002)
//   - selectedCourses[] checkbox group, one per Course row, value = CourseID
//
// "the seeded course selected" expands to a single selectedCourses entry with
// the rw-005 SEED_COURSE_ID (99001) so the new instructor is attached to the
// existing Reader-Visible Seed Course.

When(
  'I POST a new instructor with LastName {string} FirstMidName {string} HireDate {string} OfficeAssignmentLocation {string} and the seeded course selected',
  async function (
    this: ContosoWorld,
    lastName: string,
    firstMidName: string,
    hireDate: string,
    officeLocation: string
  ) {
    const token = (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken;
    assert.ok(
      token,
      'No anti-forgery token cached — preceding "I have obtained an anti-forgery token" step did not run.'
    );
    const params = new URLSearchParams();
    params.append('__RequestVerificationToken', token);
    params.append('LastName', lastName);
    params.append('FirstMidName', firstMidName);
    params.append('HireDate', hireDate);
    params.append('OfficeAssignment.Location', officeLocation);
    params.append('selectedCourses', SEED_COURSE_ID);
    await this.request('POST', '/Instructors/Create', {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params
    });
  }
);

// --- POST /Instructors/Edit/{id} with cleared OfficeAssignment + zero courses
//
// "no courses selected" omits the selectedCourses parameter entirely so the
// controller sees `string[] selectedCourses == null` (legacy parity with
// FR-F-003-004 — null array means "remove all assignments").
// "OfficeAssignmentLocation \"\"" posts an empty string so the
// IsNullOrWhiteSpace check in FR-F-003-003 sets OfficeAssignment to null,
// which EF Core translates into a DELETE.

When(
  'I POST the seeded instructor edit form with LastName {string} FirstMidName {string} HireDate {string} OfficeAssignmentLocation {string} and no courses selected',
  async function (
    this: ContosoWorld,
    lastName: string,
    firstMidName: string,
    hireDate: string,
    officeLocation: string
  ) {
    const id = (this as unknown as { __seedInstructorId?: string }).__seedInstructorId;
    assert.ok(id, 'Seeded instructor ID not resolved — call "I have resolved the seeded instructor ID" first.');
    const token = (this as unknown as { __antiForgeryToken?: string }).__antiForgeryToken;
    assert.ok(
      token !== undefined,
      'No anti-forgery token cached — preceding "I have obtained an anti-forgery token" step did not run.'
    );
    const params = new URLSearchParams();
    params.append('__RequestVerificationToken', token!);
    params.append('LastName', lastName);
    params.append('FirstMidName', firstMidName);
    params.append('HireDate', hireDate);
    params.append('OfficeAssignment.Location', officeLocation);
    // No selectedCourses parameter — controller sees null.
    await this.request('POST', `/Instructors/Edit/${id}`, {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params
    });
  }
);
